# Generated by Django 5.2.5 on 2025-08-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='modalidad',
            field=models.CharField(choices=[('PRE', 'Presencial'), ('VIR', 'Virtual'), ('MIX', 'Mixta')], max_length=3, verbose_name='Modalidad'),
        ),
    ]
