# Generated by Django 5.2.5 on 2025-08-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0002_alter_aprendiz_options_remove_aprendiz_programa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='documento_identidad',
            field=models.CharField(max_length=20, unique=True, verbose_name='Documento de Identidad'),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='aprendizcurso',
            name='nota_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota Final'),
        ),
    ]
