# Generated by Django 5.2.5 on 2025-08-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aula', models.CharField(max_length=50, unique=True, verbose_name='Número de Aula')),
                ('nombre_aula', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Aula')),
                ('tipo_aula', models.CharField(choices=[('teorica', 'Aula Teórica'), ('laboratorio', 'Laboratorio'), ('taller', 'Taller'), ('auditorio', 'Auditorio'), ('sala_computo', 'Sala de Cómputo'), ('biblioteca', 'Biblioteca'), ('multiproposito', 'Multipropósito')], max_length=20, verbose_name='Tipo de Aula')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad')),
                ('sede', models.CharField(choices=[('sede_principal', 'Centro Minero'), ('sede_norte', 'CEDEAGRO'), ('sede_sur', 'CEGAFE'), ('sede_centro', 'Sede Sogamoso')], max_length=50, verbose_name='Localización')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'En Mantenimiento'), ('fuera_servicio', 'Fuera de Servicio')], default='disponible', max_length=20, verbose_name='Estado')),
                ('equipamiento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Equipos Disponibles')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Adicional')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['numero_aula'],
            },
        ),
    ]
